dist: xenial
language: python
python:
- '3.5'
- '3.6'
- '3.7'
- '3.8'
- pypy3.5
install:
- pip install .
script: python setup.py test
deploy:
  provider: pypi
  username: __token__
  distributions: sdist bdist_wheel
  skip_existing: true
  on:
    tags: true
  password:
    secure: PLiOjGDJzXku9dFkgcDhbT3nUbGHGM5Ztv5JZ3arsp7wPsp7zgK8sQASWpyGzdMnm8Anpl8FaguYnGY3YVCGoxmS6yP2SkM8fNGhnjwsmLRTsf9/qpwu+1YkYjLuu6zYTEBSptqDEJlrXPyUkP9316ipBx0HtZdnZ9iDtwkX9mIBQPzKSkIQy2+4HA29nQx29XlgSX0dfc7HsZ8GMl2rRR0YE5V+W1b+tI0vB+WLGwi3CfNAV1+uKZ9P25CQZXCRTW6cYRe55hXU2RvpHOt8pnt60/ronjfN+B2nYs/GyLwFbdW0XznfrDFXNyL4llZ9LevRY3t7ksYLryALmO7PATCt+4gfzUpET0uPbrjXPUROTRTFY1hCU/sewdYRFYLjla9e30big/s5e50ilg56pHtDVFVnQqWA/EqzG1n+IVqexJTXlHQ/vrVQVP/B/z9VBBE/ON4iugeJ7Awl+HtSXq/S4lWQl0S2sYEnO8gLBHHh6mG6uPM79aqpWCO9mkM5pdbJibB4dLyU/cJIUHwlchRV/yrpHYxIPI2Uprw2stYn+30T8g75LKTFu1yu7o+wvn8BzeTXPwxLSnlcZtr1Gm+PZfukFaSO6v5sJSa2VV+OZunXdIvxPvD+ruVrMWAmtzZD3vy19iL3B4V8nHj8RNj4JFDR91yPijKkCMGFIpk=
